### PR TITLE
Fix #190 non entity internal links

### LINKED ISSUE #190: Adding a link to <front> in service sub-landing page causes 500 error when page renders
When adding child pages to a service sub-landing page, the help text under the URL states:

> Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. **Enter \<front\> to link to the front page**. Enter \<nolink\> to display link text only. Enter \<button\> to display keyboard-accessible link text only.

However, entering `<front>` in this field causes the page to error when viewed.

### Steps to replicate

1. Create, or open an existing, Service Sub-Landing Page
2. Navigate to "Child Pages"
3. Enter `<front>` as the URL
4. Save content
5. Navigate to page

### Expected behaviour

Page renders with a link to the home page

### Observed behaviour

500 error, text stating:

> The website encountered an unexpected error. Please try again later.

"Recent log messages" shows:

> Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 139 of /var/www/html/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php).

### PR DESCRIPTION
**Pull request by ekes**
Changes logic for internal links to make a best guess attempt about the route being an entity route and renders as it was if it is; but falls back if there isn't a match to rendering an internal link normally.

### CODE REVIEW

**Comment by ekes** [comment]
@Adnan-cds I'll add you as reviewer as you wrote the original code?
@andybroomfield You had the issue #185 I guess this should fix that too?
@keelanfh And it fixes #190 for you?

**Comment by keelanfh** [comment]
Tested and can confirm this fixes #190 for me. Great work! 👍

**Comment by ekes** [comment]
The failing test there is:-
> 1) Drupal\Tests\localgov_services_navigation\FunctionalJavascript\EntityReferenceServicesAutocompleteTest::testEntityReferenceAutocompleteWidget
> Failed asserting that actual size 2 matches expected size 1.
>
> /var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:122
> /var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:55
> /var/www/html/web/modules/contrib/localgov_services/modules/localgov_services_navigation/tests/src/FunctionalJavascript/EntityReferenceServicesAutocompleteTest.php:177
>/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:728

It doesn't fail locally. And it doesn't look like it could be related to any changes made in the branch. Any ideas? @stephen-cox @Adnan-cds @andybroomfield maybe?

**Comment by finnlewis** [comment]
Nice work @ekes  - I've not tested it but glad it works for @keelanfh 

Let's let @Adnan-cds  and/or @andybroomfield review before getting it merged and released.

And thanks for reporting this @keelanfh - Open Source in action!

File: modules/localgov_services_sublanding/src/Plugin/Field/FieldFormatter/LinkNodeReference.php [hunk 1]
```diff
@@ -142,41 +143,64 @@ private function buildExternal(LinkItem $item) {
...
+      if ($entity) {
+        return $this->buildEntityLink($entity);
       }
       else {
-        return [$is_published = FALSE, []];
+        $render_array = [
+          '#theme' => 'dummy_teaser',
+          '#title' => $item->getValue()['title'],
+          '#url' => $url,
+        ];
```
Comment (Adnan-cds) [inline modules/localgov_services_sublanding/src/Plugin/Field/FieldFormatter/LinkNodeReference.php:170]: This appear to be duplicating ::buildExternal().  A direct call to buildExternal() may be better.

File: modules/localgov_services_sublanding/tests/src/Functional/LinkFormatterTest.php [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+    $this->assertSession()->statusCodeEquals(200);
+    $this->assertSession()->pageTextContains($this->serviceSubPage->getTitle());
+    $this->assertEquals('https://example.com', $this->getSession()->getPage()->findLink('Example external link')->getAttribute('href'));
+    $this->assertSession()->ResponseNotContains('localgov-services-sublanding-child-entity--unpublished');
+  }
+
+  /**
+   * Test link formatter with an internal, non-node, link.
+   */
+  public function testInternal() {
```
Comment (Adnan-cds) [inline modules/localgov_services_sublanding/tests/src/Functional/LinkFormatterTest.php]: testInternalNonNode() may be a more meaningful name.

**Review by Adnan-cds — COMMENTED** [review]
Looking good to me :)

**Comment by andybroomfield** [comment]
Is working for me, so this is good pending tests passing.

File: modules/localgov_services_sublanding/src/Plugin/Field/FieldFormatter/LinkNodeReference.php (hunk 1 above)
Comment (ekes) [reply modules/localgov_services_sublanding/src/Plugin/Field/FieldFormatter/LinkNodeReference.php:170]: It's not quite duplicating it as it's already got a \Drupal\Core\Url object, it doesn't need recreating. Plus it is an internal link not an external one. I was wondering if it might not be possible to get even more useful info out of the object but left it at that for now.

**Comment by ekes** [comment]
> Is working for me, so this is good pending tests passing.

Yes so that. The fail I mention above https://github.com/localgovdrupal/localgov_services/pull/191#issuecomment-1377374486 Can anyone recreate that. Why does it happen here?

**Comment by Adnan-cds** [comment]
I am okay with the code now.  I haven't verified the issues with the tests.  If you are satisfied with the test situation, I won't mind if you merge this.  Thanks.

**Comment by ekes** [comment]
OK this test fails (in the github run tests not locally) also on https://github.com/localgovdrupal/localgov_services/actions/runs/3874985618/jobs/6606933816 so it's not related to this issue or code.

**Comment by finnlewis** [comment]
Sounds like @Adnan-cds and @ekes are happy, so let's get this merged today.

**Comment by ekes** [comment]
I've made a separate issue for this test https://github.com/localgovdrupal/localgov_services/issues/192

**Review by finnlewis — APPROVED** [review]
Sounds like the tests are failing due to something else. We're happy for this to be merged! Thanks @ekes and @Adnan-cds
