### PR TITLE
fix: phpstan issues

### LINKED ISSUE #224: Drupal 10, PHP 8.2 and PHPStan issues
The work on https://github.com/localgovdrupal/localgov_project/pull/131 has highlighted some PHP 8.2 and PHPStan issues which need fixing.

```
 ------ ------------------------------------------------------------------------------------------------------------------------ 
  Line   modules/contrib/localgov_services/modules/localgov_services_landing/tests/src/Functional/ServicesLandingPageTest.php    
 ------ ------------------------------------------------------------------------------------------------------------------------ 
  41     Access to an undefined property Drupal\Tests\localgov_services_landing\Functional\ServicesLandingPageTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                    
  51     Access to an undefined property Drupal\Tests\localgov_services_landing\Functional\ServicesLandingPageTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                    
 ------ ------------------------------------------------------------------------------------------------------------------------ 

 ------ -------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_services/modules/localgov_services_page/tests/src/Functional/ServicesPageTest.php    
 ------ -------------------------------------------------------------------------------------------------------------- 
  40     Access to an undefined property Drupal\Tests\localgov_services_page\Functional\ServicesPageTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                          
  50     Access to an undefined property Drupal\Tests\localgov_services_page\Functional\ServicesPageTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                          
 ------ -------------------------------------------------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_services/modules/localgov_services_status/tests/src/Functional/ServiceStatusTest.php    
 ------ ----------------------------------------------------------------------------------------------------------------- 
  51     Access to an undefined property Drupal\Tests\localgov_services_status\Functional\ServiceStatusTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                             
  67     Access to an undefined property Drupal\Tests\localgov_services_status\Functional\ServiceStatusTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                             
  131    Access to an undefined property Drupal\Tests\localgov_services_status\Functional\ServiceStatusTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                             
 ------ ----------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_services/modules/localgov_services_status/tests/src/Kernel/PathTest.php        
 ------ -------------------------------------------------------------------------------------------------------- 
  52     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  65     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  68     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  71     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  74     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  82     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  85     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  88     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
  91     Access to an undefined property Drupal\Tests\localgov_services_status\Kernel\PathTest::$pathProcessor.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                    
 ------ -------------------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_services/modules/localgov_services_sublanding/tests/src/Functional/LinkFormatterTest.php           
 ------ ---------------------------------------------------------------------------------------------------------------------------- 
  97     Access to an undefined property Drupal\tests\localgov_services_sublanding\Functional\LinkFormatterTest::$childPageLastNid.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                        
 ------ ---------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_services/modules/localgov_services_sublanding/tests/src/Functional/ServiceSublandingTest.php    
 ------ ------------------------------------------------------------------------------------------------------------------------- 
  39     Access to an undefined property Drupal\Tests\localgov_services_sublanding\Functional\ServiceSublandingTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                     
  50     Access to an undefined property Drupal\Tests\localgov_services_sublanding\Functional\ServiceSublandingTest::$adminUser.  
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property                                     
 ------ ------------------------------------------------------------------------------------------------------------------------- 
```

### PR DESCRIPTION
**Pull request by millnut**
Fix issues reported in https://github.com/localgovdrupal/localgov_services/issues/224

### CODE REVIEW

File: modules/localgov_services_sublanding/tests/src/Functional/LinkFormatterTest.php [hunk 1]
```diff
@@ -94,7 +94,6 @@ public function testNode() {
         ],
       ],
     ]);
-    $this->childPageLastNid = $child_page->id();
```
Comment (millnut) [inline modules/localgov_services_sublanding/tests/src/Functional/LinkFormatterTest.php:97]: Removed as didn't appear to be used

**Review by finnlewis — APPROVED** [review]
Tests pass, looks good. Thanks @millnut !
